name: cron test
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: curl --request GET --url 'https://oscar-react-app.vercel.app/api/endpoints/verify_payment'
